import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogFooter,
} from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Switch } from "@/components/ui/switch";
import { useState } from "react";
import { useMutation } from "@tanstack/react-query";
import { apiRequest, queryClient } from "@/lib/queryClient";
import { useToast } from "@/hooks/use-toast";
import { useAuth } from "@/hooks/use-auth";
import { Loader2 } from "lucide-react";
import JobPreviewModal from "./job-preview-modal";

interface HiringIntakeFormProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
}

export default function HiringIntakeForm({ open, onOpenChange }: HiringIntakeFormProps) {
  const { user } = useAuth();
  const { toast } = useToast();
  const [jobTitle, setJobTitle] = useState("");
  const [roleType, setRoleType] = useState("Full-time");
  const [urgency, setUrgency] = useState("Normal (Within a month)");
  const [skills, setSkills] = useState("");
  const [teamContext, setTeamContext] = useState("");
  const [expressReview, setExpressReview] = useState(false);
  const [previewOpen, setPreviewOpen] = useState(false);
  const [generatedJob, setGeneratedJob] = useState<any>(null);

  const generateJobMutation = useMutation({
    mutationFn: async (jobData: any) => {
      const res = await apiRequest("POST", "/api/jobs", jobData);
      return await res.json();
    },
    onSuccess: (data) => {
      // Show preview modal with generated job description
      setGeneratedJob(data);
      setPreviewOpen(true);
      
      // Invalidate jobs query to refresh jobs list
      queryClient.invalidateQueries({ queryKey: ['/api/jobs'] });
      
      toast({
        title: "Job description generated",
        description: "Please review and approve the generated job description.",
      });
    },
    onError: (error: Error) => {
      toast({
        title: "Failed to generate job description",
        description: error.message,
        variant: "destructive",
      });
    },
  });

  const handleSubmit = () => {
    if (!jobTitle.trim()) {
      toast({
        title: "Validation error",
        description: "Job title is required",
        variant: "destructive",
      });
      return;
    }

    generateJobMutation.mutate({
      title: jobTitle,
      type: roleType,
      urgency,
      skills,
      teamContext,
      expressReview,
      submitterId: user?.id,
      description: "", // Will be generated by the server
      status: "draft"
    });
  };

  const handleClosePreview = () => {
    setPreviewOpen(false);
    onOpenChange(false);
  };

  return (
    <>
      <Dialog open={open} onOpenChange={onOpenChange}>
        <DialogContent className="sm:max-w-2xl max-h-[90vh] flex flex-col">
          <DialogHeader>
            <DialogTitle>New Hiring Request</DialogTitle>
            <DialogDescription>
              Fill out the form below to create a new job posting. The system will automatically generate a job description based on your input.
            </DialogDescription>
          </DialogHeader>
          
          <div className="space-y-6 mt-4 overflow-y-auto flex-1 pr-2">
            <div>
              <Label htmlFor="job-title">Job Title</Label>
              <Input
                id="job-title"
                placeholder="e.g. Senior Full Stack Developer"
                value={jobTitle}
                onChange={(e) => setJobTitle(e.target.value)}
              />
            </div>
            
            <div>
              <Label htmlFor="role-type">Role Type</Label>
              <Select value={roleType} onValueChange={setRoleType}>
                <SelectTrigger id="role-type">
                  <SelectValue placeholder="Select role type" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="Full-time">Full-time</SelectItem>
                  <SelectItem value="Part-time">Part-time</SelectItem>
                  <SelectItem value="Contract">Contract</SelectItem>
                  <SelectItem value="Internship">Internship</SelectItem>
                </SelectContent>
              </Select>
            </div>
            
            <div>
              <Label htmlFor="urgency">Hiring Urgency</Label>
              <Select value={urgency} onValueChange={setUrgency}>
                <SelectTrigger id="urgency">
                  <SelectValue placeholder="Select urgency" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="Critical (Need ASAP)">Critical (Need ASAP)</SelectItem>
                  <SelectItem value="High (Within 2 weeks)">High (Within 2 weeks)</SelectItem>
                  <SelectItem value="Normal (Within a month)">Normal (Within a month)</SelectItem>
                  <SelectItem value="Low (Ongoing)">Low (Ongoing)</SelectItem>
                </SelectContent>
              </Select>
            </div>
            
            <div>
              <Label htmlFor="skills">Required Skills / KPIs</Label>
              <Textarea
                id="skills"
                placeholder="List key skills, experience, and performance indicators"
                rows={3}
                value={skills}
                onChange={(e) => setSkills(e.target.value)}
              />
            </div>
            
            <div>
              <Label htmlFor="team-context">Team Context</Label>
              <Textarea
                id="team-context"
                placeholder="Briefly describe the team this person will join"
                rows={2}
                value={teamContext}
                onChange={(e) => setTeamContext(e.target.value)}
              />
            </div>
            
            <div className="flex items-center space-x-2">
              <Switch
                id="express-review"
                checked={expressReview}
                onCheckedChange={setExpressReview}
              />
              <Label htmlFor="express-review">
                Express Review (Skip 3-hour delay for assessment delivery)
              </Label>
            </div>
          </div>
          
          <DialogFooter>
            <Button variant="outline" onClick={() => onOpenChange(false)}>
              Cancel
            </Button>
            <Button 
              onClick={handleSubmit}
              disabled={generateJobMutation.isPending}
            >
              {generateJobMutation.isPending ? (
                <>
                  <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                  Generating...
                </>
              ) : (
                "Generate Job Description"
              )}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
      
      {generatedJob && (
        <JobPreviewModal
          open={previewOpen}
          onOpenChange={setPreviewOpen}
          job={generatedJob}
          onClose={handleClosePreview}
        />
      )}
    </>
  );
}
